In [198]:
import pandas as pd
import numpy as np
from pathlib import Path

folder = Path("../output_csv")

input_file = folder / "residential.csv"

df = pd.read_csv(input_file, low_memory=False)

df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,source_month
0,TheInlandGateway,TheInlandGateway,NaN,True,NaN,NaN,False,889000.0,523319952,hutton@cbappteam.com,...,9600.0,0.0,True,2.0,Rim of the World,92352,0.0,9600.0,NaN,202506
1,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,NaN,NaN,False,1899999.0,1118606385,chase.campen@compass.com,...,10400.0,NaN,False,NaN,NaN,90046,NaN,10400.0,NaN,202506
2,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1118606192,stanleylo@greenbanker.com,...,22505.0,NaN,False,3.0,Other,94010,NaN,22505.0,NaN,202506
3,PacificWest,PacificWest,NaN,True,NaN,NaN,False,865000.0,1118604114,matt@majorleaguesocal.com,...,4800.0,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,0.0,4800.0,NaN,202506
4,BayEast,BayEast,"Carpet,Laminate",NaN,NaN,NaN,False,875000.0,1118603794,brianrowland.homes@gmail.com,...,5500.0,NaN,False,4.0,NaN,94546,NaN,5500.0,NaN,202506

In [199]:
df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'source_month'],
      dtype='object')

### Clean Invalid Values

In [200]:
df = df[
    (df['ClosePrice'].notna()) &
    (df['ClosePrice'] > 0)
]


df = df[df['LivingArea'] > 0]
df = df[df['BedroomsTotal'] > 0]
df = df[df['BathroomsTotalInteger'] > 0]
df = df[df['DaysOnMarket'] >= 0]
df = df[df["ClosePrice"] > 0]

In [201]:
missing_table = pd.DataFrame({
    'missing_count': df.isna().sum(),
    'missing_percent': df.isna().mean() * 100
})

missing_table = missing_table.sort_values('missing_percent', ascending=False)

missing_table

                              missing_count  missing_percent
CoveredSpaces                        142852            100.0
MiddleOrJuniorSchoolDistrict         142852            100.0
AboveGradeFinishedArea               142852            100.0
FireplacesTotal                      142852            100.0
TaxYear                              142852            100.0
...                                     ...              ...
BathroomsTotalInteger                     0              0.0
ListingId                                 0              0.0
PropertySubType                           0              0.0
ListingKeyNumeric                         0              0.0
source_month                              0              0.0

[79 rows x 2 columns]

In [202]:

missing_cols = missing_table[missing_table['missing_percent'] >= 86].index.tolist()

missing_cols


missing = missing_table[missing_table['missing_percent'] >= 86]

missing

                              missing_count  missing_percent
CoveredSpaces                        142852       100.000000
MiddleOrJuniorSchoolDistrict         142852       100.000000
AboveGradeFinishedArea               142852       100.000000
FireplacesTotal                      142852       100.000000
TaxYear                              142852       100.000000
ElementarySchoolDistrict             142852       100.000000
BusinessType                         142852       100.000000
TaxAnnualAmount                      142852       100.000000
WaterfrontYN                         142779        99.948898
BelowGradeFinishedArea               141831        99.285274
BasementYN                           139399        97.582813
BuilderName                          136380        95.469437
LotSizeDimensions                    133854        93.701173
BuildingAreaTotal                    133343        93.343460
CoBuyerAgentFirstName                129407        90.588161
ElementarySchool                     124243        86.973231
MiddleOrJuniorSchool                 124061        86.845826

In [203]:
df = df.drop(columns=missing_cols)

df

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,Levels,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,source_month
0,TheInlandGateway,TheInlandGateway,NaN,True,False,889000.0,523319952,hutton@cbappteam.com,2025-06-13,890000.0,...,Two,9600.00,0.0,True,2.0,Rim of the World,92352,0.0,9600.0,202506
1,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,True,False,1899999.0,1118606385,chase.campen@compass.com,2025-06-30,1876384.0,...,Two,10400.00,NaN,False,NaN,NaN,90046,NaN,10400.0,202506
2,Mlslistings,Mlslistings,NaN,False,NaN,NaN,1118606192,stanleylo@greenbanker.com,2025-06-30,4820000.0,...,NaN,22505.00,NaN,False,3.0,Other,94010,NaN,22505.0,202506
3,PacificWest,PacificWest,NaN,True,False,865000.0,1118604114,matt@majorleaguesocal.com,2025-06-30,865000.0,...,One,4800.00,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,0.0,4800.0,202506
4,BayEast,BayEast,"Carpet,Laminate",NaN,False,875000.0,1118603794,brianrowland.homes@gmail.com,2025-06-30,875000.0,...,One,5500.00,NaN,False,4.0,NaN,94546,NaN,5500.0,202506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143073,HighDesert,HighDesert,NaN,True,False,85000.0,1077293793,trustdee@aol.com,2026-06-04,40000.0,...,One,5100.00,4.0,False,0.0,Needles Unified School District,92363,0.0,5100.0,202606
143074,TheInlandGateway,TheInlandGateway,"Carpet,Vinyl",True,False,1150000.0,1076795790,mikedolan@bigbearproperties.com,2026-06-25,865000.0,...,Two,19.94,1.0,False,2.0,Bear Valley Unified,92314,0.0,868586.4,202606
143075,Mrmls,OrangeCounty,NaN,True,False,825000.0,1076159305,clarkef@newportpacific.com,2026-06-22,280000.0,...,ThreeOrMore,11433.00,0.0,False,2.0,Gold Oak Union,95321,98.0,11433.0,202606
143076,Oakland,Oakland,"Carpet,Laminate",NaN,False,975000.0,1035814040,phil.fair@corcoranicon.com,2026-06-11,595000.0,...,Two,4389.00,NaN,False,1.0,Oakland,94608,NaN,4389.0,202606
143077,NorthSanLuisObispo,NorthSanLuisObispo,NaN,True,False,6989995.0,1014091927,billiejo1958@gmail.com,2026-06-26,3000000.0,...,One,2452.63,3.0,False,1.0,Paso Robles Joint Unified,93461,0.0,106836562.8,202606

In [204]:
target = 'ClosePrice'

numeric_cols = [
    'LivingArea',
    'DaysOnMarket',
    'LotSizeSquareFeet',
    'YearBuilt',
    'BathroomsTotalInteger',
    'BedroomsTotal',
    'GarageSpaces',
    'ParkingTotal',
    'Latitude',
    'Longitude',
    'Stories',
    'MainLevelBedrooms',
    'AssociationFee',
    'LotSizeAcres'
]

categorical_cols = [
    'City',
    'CountyOrParish',
    'MLSAreaMajor',
    'SubdivisionName',
    'HighSchoolDistrict',
    'HighSchool',
    'Levels',
    'PostalCode',
    'AssociationFeeFrequency',
    'StateOrProvince'
]

binary_cols = [
    'PoolPrivateYN',
    'FireplaceYN',
    'NewConstructionYN',
    'AttachedGarageYN',
    'ViewYN'
]

Pros: Dropping missing values is simple and easier to explain. If only a small portion of observations is missing, removing those rows may not substantially change the results. ]

Cons: Dropping too early or too broadly can remove observations that are still useful. If you drop every row with any missing value, you may lose a large amount of data, especially in datasets with many columns. some missing values may actually be meaningful, dropping them could make the dataset less representative.

model_cols = [
    'ClosePrice',
    'LivingArea',
    'BedroomsTotal',
    'BathroomsTotalInteger',
    'LotSizeSquareFeet',
    'YearBuilt',
    'DaysOnMarket',
    'City',
    'CountyOrParish',
    'PostalCode',
    'source_month'
]

model_cols = [col for col in model_cols if col in df.columns]

df_model = df[model_cols].copy()
df_model.head()

Pros:

Keeps more rows in the dataset.
Useful when a column is important but has some missing values.
Median imputation works well for skewed data like LivingArea, LotSizeSquareFeet, or TaxAnnualAmount.
Allows the model to still use partially complete records.

Cons:

You are filling in values that were not actually observed.
Mean/median imputation can reduce natural variation in the data.
If too much data is missing, imputation may become misleading.
Simple imputation does not always capture the true relationship between variables.

In [205]:
target = 'ClosePrice'

numeric_cols = [
    'LivingArea',
    'DaysOnMarket',
    'LotSizeSquareFeet',
    'YearBuilt',
    'BathroomsTotalInteger',
    'BedroomsTotal',
    'GarageSpaces',
    'Latitude',
    'Longitude',
    'FireplacesTotal',
    'TaxAnnualAmount',
    'AssociationFee',
    'Stories',
    'MainLevelBedrooms'
]

categorical_cols = [
    'City',
    'CountyOrParish',
    'MLSAreaMajor',
    'SubdivisionName',
    'HighSchoolDistrict',
    'ElementarySchoolDistrict',
    'Levels',
    'PostalCode'
]

binary_cols = [
    'PoolPrivateYN',
    'FireplaceYN',
    'NewConstructionYN',
    'AttachedGarageYN',
    'ViewYN',
    'WaterfrontYN',
    'BasementYN'
]

# Keep only columns that exist in the dataframe
numeric_cols = [col for col in numeric_cols if col in df.columns]
categorical_cols = [col for col in categorical_cols if col in df.columns]
binary_cols = [col for col in binary_cols if col in df.columns]

keep_cols = [target, 'source_month'] + numeric_cols + categorical_cols + binary_cols
df = df[keep_cols].copy()

df.head()

,ClosePrice,source_month,LivingArea,DaysOnMarket,LotSizeSquareFeet,YearBuilt,BathroomsTotalInteger,BedroomsTotal,GarageSpaces,Latitude,...,MLSAreaMajor,SubdivisionName,HighSchoolDistrict,Levels,PostalCode,PoolPrivateYN,FireplaceYN,NewConstructionYN,AttachedGarageYN,ViewYN
0,890000.0,202506,3000.0,181,9600.0,2021.0,3.0,3.0,2.0,34.264692,...,287A - Arrowhead Woods,NaN,Rim of the World,Two,92352,False,True,True,True,True
1,1876384.0,202506,1800.0,87,10400.0,1963.0,3.0,3.0,NaN,34.107983,...,C03 - Sunset Strip - Hollywood Hills West,NaN,NaN,Two,90046,False,True,False,False,True
2,4820000.0,202506,4270.0,0,22505.0,1980.0,6.0,6.0,3.0,37.567434,...,699 - Not Defined,NaN,Other,NaN,94010,NaN,True,False,True,False
3,865000.0,202506,1442.0,0,4800.0,1985.0,2.0,3.0,2.0,33.906058,...,85 - Yorba Linda,other,Placentia-Yorba Linda Unified,One,92886,False,True,False,True,True
4,875000.0,202506,1086.0,0,5500.0,1953.0,1.0,3.0,4.0,37.705919,...,NaN,CASTRO VALLEY,NaN,One,94546,False,True,False,True,NaN

In [206]:
# remove extreme outliers 

outlier_cols = [target] + numeric_cols

for col in outlier_cols:
    upper = df[col].quantile(0.99)
    df_model = df[df[col].isna() | (df[col] <= upper)]

df.shape

(142852, 26)

In [207]:
# Handle missing numeric values with flags + median imputation

for col in numeric_cols:
    df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
    df_model[col] = df_model[col].fillna(df_model[col].median())

#This lets you keep the row, but also preserves whether the value was originally missing.

C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\1962982861.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(df_model[col].median())

In [208]:
#Encode binary Y/N columns

for col in binary_cols:
    df_model[col] = df_model[col].map({
        'Y': 1,
        'N': 0,
        True: 1,
        False: 0,
        'True': 1,
        'False': 0,
        'true': 1,
        'false': 0
    })

    df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
    df_model[col] = df_model[col].fillna(0)

C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].map({
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(0)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].map({
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(0)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].map({
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(0)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].map({
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(0)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].map({
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col + '_missing_flag'] = df_model[col].isna().astype(int)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3996563423.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna(0)

In [209]:
# Handle categorical missing values
for col in categorical_cols:
    df_model[col] = df_model[col].fillna('Unknown').astype(str)

#To avoid creating too many dummy columns, group rare values as "Other":

for col in categorical_cols:
    top_values = df_model[col].value_counts().head(25).index
    df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')

C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna('Unknown').astype(str)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna('Unknown').astype(str)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna('Unknown').astype(str)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna('Unknown').astype(str)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna('Unknown').astype(str)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna('Unknown').astype(str)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].fillna('Unknown').astype(str)
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\3813263999.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_model[col] = df_model[col].where(df_model[col].isin(top_values), 'Other')

In [210]:
# One-hot encode categorical columns
df_encoded = pd.get_dummies(
    df_model,
    columns=categorical_cols,
    drop_first=True
)

df_encoded.head()

,ClosePrice,source_month,LivingArea,DaysOnMarket,LotSizeSquareFeet,YearBuilt,BathroomsTotalInteger,BedroomsTotal,GarageSpaces,Latitude,...,PostalCode_92584,PostalCode_92592,PostalCode_92596,PostalCode_93065,PostalCode_93446,PostalCode_93535,PostalCode_93536,PostalCode_93551,PostalCode_94513,PostalCode_Other
0,890000.0,202506,3000.0,181,9600.0,2021.0,3.0,3.0,2.0,34.264692,...,False,False,False,False,False,False,False,False,False,True
1,1876384.0,202506,1800.0,87,10400.0,1963.0,3.0,3.0,2.0,34.107983,...,False,False,False,False,False,False,False,False,False,True
2,4820000.0,202506,4270.0,0,22505.0,1980.0,6.0,6.0,3.0,37.567434,...,False,False,False,False,False,False,False,False,False,True
3,865000.0,202506,1442.0,0,4800.0,1985.0,2.0,3.0,2.0,33.906058,...,False,False,False,False,False,False,False,False,False,True
4,875000.0,202506,1086.0,0,5500.0,1953.0,1.0,3.0,4.0,37.705919,...,False,False,False,False,False,False,False,False,False,True

In [211]:
# Train/test split by most recent month
df_encoded['source_month'] = df_encoded['source_month'].astype(float).astype(int).astype(str)

months = sorted(df_encoded['source_month'].unique())

test_month = months[-1]

print("Available months:", months)
print("Test month:", test_month)

Available months: ['202506', '202507', '202508', '202509', '202510', '202511', '202512', '202601', '202602', '202603', '202604', '202605', '202606']
Test month: 202606

In [212]:
X_window = 6

train_months = months[-(X_window + 1):-1]

train_df = df_encoded[df_encoded['source_month'].isin(train_months)].copy()
test_df = df_encoded[df_encoded['source_month'] == test_month].copy()

print("Training months:", train_months)
print("Testing month:", test_month)
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Training months: ['202512', '202601', '202602', '202603', '202604', '202605']
Testing month: 202606
Train shape: (61429, 202)
Test shape: (12793, 202)

In [213]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

drop_cols = [target, 'source_month']
feature_cols = [col for col in df_encoded.columns if col not in drop_cols]

results = []

for X_window in [3, 6, 9, 12]:
    train_months = months[-(X_window + 1):-1]
    test_month = months[-1]

    train_df = df_encoded[df_encoded['source_month'].isin(train_months)].copy()
    test_df = df_encoded[df_encoded['source_month'] == test_month].copy()

    X_train = train_df[feature_cols]
    y_train = train_df[target]

    X_test = test_df[feature_cols]
    y_test = test_df[target]

    log_columns = [
    "LivingArea",
    "LotSizeSquareFeet",
    "DaysOnMarket",
    "AssociationFee",
    "TaxAnnualAmount"
] 
    log_columns = [
    column
    for column in log_columns
    if column in X_train.columns
] 
    X_train[log_columns] = np.log1p(
    X_train[log_columns])


    X_test[log_columns] = np.log1p(
    X_test[log_columns]
)
    


    

    

    



    model = LinearRegression()
    model.fit(X_train, y_train)

    preds = model.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2 = r2_score(y_test, preds)

    results.append({
        'training_window_months': X_window,
        'train_months': ', '.join(train_months),
        'test_month': test_month,
        'mae': mae,
        'rmse': rmse,
        'r2': r2
    })

results_df = pd.DataFrame(results)
results_df.sort_values('mae')

C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[log_columns] = np.log1p(
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[log_columns] = np.log1p(
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[log_columns] = np.log1p(
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[log_columns] = np.log1p(
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[log_columns] = np.log1p(
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[log_columns] = np.log1p(
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[log_columns] = np.log1p(
C:\Users\luoxu\AppData\Local\Temp\ipykernel_29856\4084115474.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[log_columns] = np.log1p(

,training_window_months,train_months,test_month,mae,rmse,r2
3,12,"202506, 202507, 202508, 202509, 202510, 202511...",202606,559179.769689,1.139078e+06,0.450445
2,9,"202509, 202510, 202511, 202512, 202601, 202602...",202606,560305.964341,1.161726e+06,0.428376
1,6,"202512, 202601, 202602, 202603, 202604, 202605",202606,576815.627869,1.168612e+06,0.421578
0,3,"202603, 202604, 202605",202606,666880.832831,1.264678e+06,0.322572

In [214]:
output_file = folder / "residential_cleaned.csv"

df_encoded.to_csv(output_file, index=False)

print("Saved cleaned CSV to:", output_file)

Saved cleaned CSV to: ..\output_csv\residential_cleaned.csv

In [215]:
clean = pd.read_csv(output_file)
clean.head()
sample_df = clean.sample(n=100, random_state=42)
                         
folder1 = Path("../week 3")

sample_df.to_csv(folder1 / "residential_cleaned_preprocessed_sample.csv", index=False)